
spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/event-sphere
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: payment-group-v2
      auto-offset-reset: latest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.eventsphere.payment_service.event.BookingCreateEvent


server:
  port: 8099


cors:
  allowed-origins: "http://localhost:5173"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

logging:
  level:
    root: INFO
    com.eventsphere.user_service: DEBUG

razorpay:
  key: rzp_test_SBB1ElloLuHfk8
  secret: z4XUX2gZKS8ABUEOwg6J0Y2Z
