server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/bookings/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**

        - id: listing-service
          uri: lb://LISTING-SERVICE
          predicates:
            - Path=/listings/**

        - id: auth-service
          uri: lb://USER-SERVICE
          predicates:
              - Path=/auth/**
        - id: oauth2-route
          uri: lb://USER-SERVICE
          predicates:
              - Path=/oauth2/**,/login/**
      default-filters:
        - PreserveHostHeader

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

logging:
  level:
    org.springframework.cloud.gateway: INFO

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/